[package]
name = "is-graphic-rs"
version = "0.1.0"
authors = ["Vinícius Rodrigues Miguel <lemao.vrm07@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
